FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
RUN pnpm nx run cms:build

EXPOSE 4200

CMD pnpm nx run cms:serve:production

# FROM node:20-alpine AS runner
# WORKDIR /app

# COPY --from=base /app /app

# EXPOSE 3000

# CMD node dist/apps/cms/.next/standalone/apps/cms/server.js
